name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: cat
        run: cat test.json

      - name: swapfile
        run: swapoff /mnt/swapfile;mkswap /mnt/swapfile;swapon /mnt/swapfile
