name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: cat
        run: cat test.json

      - name: swapfile
        run: sudo swapon -s; sudo free -h;sudo swapoff /mnt/swapfile;sudo truncate -s 3G /mnt/swapfile;sudo mkswap /mnt/swapfile;sudo swapon /mnt/swapfile;sudo swapon -s; sudo free -h

      - name: swapfile2
        run: |
          sudo fallocate -l 2G /swapfile2;sudo chmod 600 /swapfile2;sudo mkswap /swapfile2;sudo swapon /swapfile2;sudo swapoff /mnt/swapfile
          sudo swapon -s; sudo free -h
          sudo rm /mnt/swapfile
          sudo swapon -s; sudo free -h

      - name: factory script
        run: |
          isMntSwap=$(cat /etc/waagent.conf | grep "ResourceDisk.EnableSwap=y" || true)
          echo $isMntSwap
          if [ -z "$isMntSwap" ]; then
          echo 'I am in here'
          fallocate -l 4G /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo '/swapfile none swap sw 0 0' >> /etc/fstab
          fi
          cat /etc/fstab
          cat /etc/waagent.conf
          sudo swapon -s; sudo free -h
