name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: swapon
        run: swapon -s

      - name: free
        run: free -h
      
      - name: Print available space
        run: df -h

      - name: Print disk usage
        run: du -h -d 2 /home/runner/
