name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: cat
        run: cat test.json

      - name: swapfile
        run: sudo swapon -s; sudo free -h;sudo swapoff /mnt/swapfile;sudo truncate -s 3221225472 /mnt/swapfile;sudo mkswap /mnt/swapfile;sudo swapon /mnt/swapfile;sudo swapon -s; sudo free -h
