name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: cat
        run: cat test.json

      - name: 'CGroup'
        run: |
          sudo cgrulesengd || true
          cgconfigparser --load=/etc/cgconfig.conf || true
          # print out config file
          cat /etc/cgconfig.conf || true
          
      - name: 'CGroup2'
        run: |
          sudo mkdir /etc/cgconfig.d || true
          sudo cp /etc/cgconfig.conf /etc/cgconfig.d/ || true
          cgconfigparser --load=/etc/cgconfig.conf || true
          echo 'cgrules.conf:'
          cat /etc/cgrules.conf
          echo 'daemon.json:'
          cat /etc/docker/daemon.json

      - name: OOM
        run: |
          # Get the PID of the 'provisioner' process
          PROVISIONER_PID=$(pgrep provisioner)
          # Check the current oom_score_adj value
          sudo echo "Current oom_score_adj value for provisioner: $(sudo cat /proc/$PROVISIONER_PID/oom_score_adj)"
          # Change the oom_score_adj value to -1000
          sudo echo -1000 > /proc/$PROVISIONER_PID/oom_score_adj
          # Recheck the oom_score_adj value
          sudo echo "New oom_score_adj value for provisioner: $(sudo cat /proc/$PROVISIONER_PID/oom_score_adj)"
          
