name: Test

on:
  push: 
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cat
        run: |
          set -ex
          pwd
          ls -l ./
          cat test.json

      # - name: 'Azure login'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
