name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: swapon
        run: swapon -s

      - name: free
        run: free -h
      
      - name: Print available space
        run: df -h

      - name: Print disk usage of /mnt
        run: du -h -d 2 /mnt || true

      - name: Print disk usage of /home/runner
        run: du -h -d 2 /home/runner || true

      - name: /home/runner/runners disk usage
        run: ls -lh /home/runner/runners || true
        
      - name: Print disk usage of /home
        run: du -h -d 2 /home || true

      - name: Print disk usage of /opt/hostedtoolcache
        run: du -h -d 2 /opt/hostedtoolcache || true

      - name: Print disk usage of /opt
        run: du -h -d 2 /opt || true

      - name: Print disk usage of /
        run: du -h -d 2 /
